### ISSUE TITLE
Sync button/menu option missing

### ISSUE THREAD

**Issue by sunjam** [dgmid/nextcloud-bookmark-manager#10]
Hi, noticed there is no visible sync button or option within the menu.  Also noticed the close, minimize, maximize buttons missing on MacOS 10.12.

After successfully gaining access to my account I just see this:
![Screen Shot 2019-11-10 at 8 07 17 AM](https://user-images.githubusercontent.com/1787238/68546961-2985d780-0391-11ea-9eb8-478027f20db3.png)

**Comment by dgmid** [comment]
This should now be fixed when v2.0.0 is released
