### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by LnxGnome** [dgmid/nextcloud-bookmark-manager#11]
Is there any plan to support folders?
I use floccus to sync NC bookmarks to the bookmarks tab in my (chromium based) browsers (haven't tried it with FF, yet).  Because of this, using folders instead of tags is a way of life.

**Comment by dgmid** [comment]
@LnxGnome - yes - absolutely, folders is on my todo list.

**Comment by LnxGnome** [comment]
Awesome!

**Comment by dgmid** [comment]
Folders will be supported in the next release v2.0.3
