### ISSUE TITLE
URL as a column [feature request]

### ISSUE THREAD

**Issue by LnxGnome** [dgmid/nextcloud-bookmark-manager#12]
Please add URL as a column.
This would make it easier to identify bookmarks that are very similar, especially where the Title is different.  For instance:
"Main page!"  example.com/  
"Login here"   example.com/login
"Overview"     example.com/dashboard

**Comment by dgmid** [comment]
I could re-add it, but really long urls were causing a problem - but is it really necessary to see the actual url?
What happens when you're using your browser and you access the bookmarks for the bookmarks menu - how do you tell one from the other?

**Comment by LnxGnome** [comment]
It's more useful for cleaning up the bookmarks, removing near duplicates, but not really useful for daily use.  This cleanup, and reorganizing bookmarks, is what I use a "bookmark manager" for most often.  The address bar in-browser will usually find a bookmark for me to go to when I start typing a keyword or part of a title.

If I hover over a bookmark on the in-browser (Brave) bookmark toolbar, the URL is shown in a pop-up.  In the in-browser bookmark manger, the URL shows when you select the line.  

I would not mind if the URL columns were truncated at N chars (hopefully N being set in 'settings'), as I'm thinking this is for display only, with the same checkbox at the lower left to enable/disable the column display.

I think I see the problems you mentioned, because I see problems (column headings don't match the column) with really long Titles.

BTW, cool tool!

**Comment by dgmid** [comment]
@LnxGnome OK, understood.
> truncated at N chars (hopefully N being set in 'settings')
this seems like a good way to handle it

**Comment by dgmid** [comment]
columns fixed in this commit https://github.com/dgmid/nextcloud-bookmark-manager/commit/4738057296d039457baa0749c569b1208b705980
this commit also fixes the headers sometimes not aligning with columns

<img width="1440" alt="ncbm-2 0 3-a-cols" src="https://user-images.githubusercontent.com/1267580/79312695-90d72300-7eff-11ea-9991-4e70d150bf8b.png">
