### ISSUE TITLE
multi-instance or multiple-accounts [feature request]

### ISSUE THREAD

**Issue by LnxGnome** [dgmid/nextcloud-bookmark-manager#13]
I'm a semi-organized person.  I have separate OS & Nextcloud accounts for work, school, other-work and daily-life/play (I stay a bit busy).  Similarly, I have different sets of bookmarks for each focus, and when I'm in one of work/school/other-work mode, nextcloud-bookmark-manager works really well.  However, when I'm in the daily-life focus, I tend to multitask a lot, and use multiple in-browser profiles, each relating back to the other focuses. (actually have more profiles than focuses, like finances and play are both part of daily-life, but are different browser profiles)
This means I may want to switch back and forth in nextcloud-bookmark-manager between these different Nextcloud accounts.  I guess I'm asking for an easy way to switch back and forth without having to log-off / log-on each time through nextcloud-bookmark-manager.  It would seem that adding a profile manager to nextcloud-bookmark-manager would do the trick.

**Comment by dgmid** [comment]
it's unlikely that I ill be adding such a feature in the near future
