### ISSUE TITLE
duplicate tags displayed in details

### ISSUE THREAD

**Issue by LnxGnome** [dgmid/nextcloud-bookmark-manager#14]
re: Nextcloud Bookmark Manager v2.0.2
macOS 10.15.4

Just tried out tags for the first time, by editing a bookmark in this tool.  I noticed two tags were shown instead of one.

The tag shows up just once in the edit window, as it should.
![image](https://user-images.githubusercontent.com/5316950/79244284-bbb07100-7e44-11ea-806d-7b4e0675b24e.png)

But shows up twice elsewhere.
![image](https://user-images.githubusercontent.com/5316950/79244351-cec34100-7e44-11ea-9f86-8c0a23bd5b2d.png)

It really is the only bookmark with any tags...
![image](https://user-images.githubusercontent.com/5316950/79244980-7a6c9100-7e45-11ea-8a78-6b61e1cc2705.png)

I tried removing the tag, and after hitting update and trying to select All Bookmarks, the app hung.
I stopped & restarted it, then added the tab back again, and it shows up as two tags as before.

**Comment by dgmid** [comment]
@LnxGnome  if you log in to your Nextcloud instance and open up the bookmarks app how does that bookmark show up?

**Comment by LnxGnome** [comment]
@dgmid Two "linux" tags appear on the same bookmark within Nextcloud's bookmarks app also.  I was able to remove the 2nd tag from there...
I restarted the mac app.
and the 2nd tag re-appeared on the record within the Nextcloud instance.

I stopped the mac app and then completely removed the tag using the NC webui.
I then restarted the mac app and everything looks normal again (no BMs are tagged).

I picked a different BM this time, and added a different tag to it using the mac app ...
It exhibits the same behavior as the 'linux' tag, with the tag showing twice in the mac app, and twice on the BM in the webui.  

I didn't mention it before, but the NC instance is version: 16.0.3.0, with a Bookmark app v2.3.4.  Any known issues there?

**Comment by dgmid** [comment]
I am unable to recreate this.
Are you sure about this part?

> I restarted the mac app.
_and the 2nd tag re-appeared on the record within the Nextcloud instance._

Just opening the app can't modifiy the content on your Nextcloud instance as all that happens is a GET request via the bookmarks api to get the data for all the bookmarks.

I can understand that if there is a bug in my app, it might show the same tag twice - but it can't make any changes to the NC database without actually _saving_ some data.

Do the log files show any errors (particularly render.log)? You can find them here:
`~/Library/Logs/Nextcloud Bookmark Manager/`

**Comment by dgmid** [comment]
Some other things to try:
If you create a second tag does that also show up double - or does it only happen with the first tag created?
if you create a tag in the Nextcloud app then open my app does that tag also show up double?

**Comment by LnxGnome** [comment]
> Some other things to try:
> If you create a second tag does that also show up double - or does it only happen with the first tag created?
> if you create a tag in the Nextcloud app then open my app does that tag also show up double?

second things first...
2nd tag? Yes, it shows up duplicated too.  But I think I'm on to something, or on something... which points at NC Bookmarks instead of your app.

In the WebUI, if I look at "All Bookmarks" and find an entry with a tag, it looks normal!
![image](https://user-images.githubusercontent.com/5316950/79412682-15fc1f80-7f74-11ea-90ae-4c95fb29e94e.png)

In the WebUI, if I select a tag on the lefthand side, then it is doubled up per BM (or once, quadrupled).  Seems to be something wrong on the server side here...
![image](https://user-images.githubusercontent.com/5316950/79412724-2ad8b300-7f74-11ea-9b62-a498a30b1d9e.png)

In the mac app, even when I look at "All Bookmarks", they are still showing as doubled up.  I wonder why it doesn't follow the pattern of the WebUI.
![image](https://user-images.githubusercontent.com/5316950/79413114-121ccd00-7f75-11ea-8584-287d3fa7f400.png)

I looked into the local log and it looks sane...
`
[info] CLICK - ID: 219
[info] single : /index.php/apps/bookmarks/public/rest/v2/bookmark/219
[info] response ok
[info] modify : /index.php/apps/bookmarks/public/rest/v2/bookmark/219?record_id=219&url=https%3A%2F%2Fwww.dell.com%2Fsupport%2Fhome%2Fus%2Fen%2F04%2Fproduct-support%2Fproduct%2Fpowervault-md1200%2Fmanuals&title=Support%20for%20PowerVault%20MD1200%20%7C%20Manuals%20%26%20documents%20%7C%20Dell%20US&description=&item[tags][]=dell
[info] response ok
`

**Comment by dgmid** [comment]
OK, thanks for including the log. That seems to be getting and saving correctly.
Can you have a look at this file:
`~/Library/Application Support/Nextcloud Bookmark Manager/bookmarks.json`
Find the bookmark with id of 219 and see what it's showing for tags.

I'm beginning to suspect that the problem is on the server. I can't replicate on my installation. I'm using the same version of the Bookmarks app as you but my Version on NC is `18.0.3`

Have you looked at the repo for the Bookmarks app?
https://github.com/nextcloud/bookmarks
Maybe other users have has similar problems.

**Comment by LnxGnome** [comment]
I asked last night about this over on the bookmarks app forum, https://help.nextcloud.com/t/duplicate-tags-showing-up-when-filtering-on-tags-bug-report/78023, and the reply to seeing the duplicate tags when selecting the tag filter was "this should be fixed in the upcoming version 3".

The bookmarks.json file does show a duplicate for rec 219,
```
                        "tags": [
                                "dell",
                                "dell"
                        ],
                        "folders": [
                                "32",
                                "-1"
                        ]
```

**Comment by dgmid** [comment]
Ah - OK, thanks,
I had a quick look this morning but didn't find anything. So this is definitely a problem with the Bookmarks app

You're seeing duplicates also in this app because the first thing it does on opening is update the bookmarks.json file directly from NC - and as the tags are duplicated in the data sent from NC - so they get duplicated in this app.

**Comment by dgmid** [comment]
I'm currently implementing folders in to the app, and now I can see better what is going on.
Tags get doubled for bookmarks that have been placed in more than one folder.

![tag-doubling](https://user-images.githubusercontent.com/1267580/80277623-8df2e400-86f0-11ea-89e1-2fb813cf7c48.png)

In fact in the example you sent me:
```
"folders": [
     "32",
      "-1"
 ]
```
the bookmark is in 2 folders.

Now I know how it happens I should be able to filter it out for now.
