### ISSUE TITLE
Making the window with too small corrupts the display of the BM lines.

### ISSUE THREAD

**Issue by LnxGnome** [dgmid/nextcloud-bookmark-manager#15]
NBM 2.0.2 / macOS 10.15.4

If the window is made too narrow, the line becomes somewhat hidden.  Text on the line is no longer visible, but the twisty and alternate shading of the lines is still seen.  It appears the first column containing the twisty expands to fill the window (so the Title and other columns are beyond the right edge of the window).

![image](https://user-images.githubusercontent.com/5316950/79285737-65ffb700-7e8c-11ea-8920-f7929f0162e3.png)

![image](https://user-images.githubusercontent.com/5316950/79285752-76179680-7e8c-11ea-971c-e26c21733d41.png)

I can still click on those lines and they expand to show the details of a BM.
Making the window wider again returns the width of the first column to normal.

This might be related.  The Titles on my book marks can be quite long (whatever was captured by the bookmark function in the browser).  For example: "Maytag 5.3 cu. ft. High-Efficiency White Top Load Washing Machine with Deep Clean Option, ENERGY STAR-MVWB835DW - The Home Depot"

Secondary query: Why isn't there a scrollbar at the bottom of the page if the width of the columns expands beyond the width of the window?

**Comment by dgmid** [comment]
fixed in https://github.com/dgmid/nextcloud-bookmark-manager/commit/4738057296d039457baa0749c569b1208b705980
see #12
