### ISSUE TITLE
Request for folder support

### ISSUE THREAD

**Issue by kdbruin** [dgmid/nextcloud-bookmark-manager#16]
I love the ability to use and synchronise my bookmarks between various browsers and operating systems using Nextcloud Bookmarks. For Safari there is no solution so I tried this application. Although I can access all the bookmarks it misses the ability to organise them using the folders I have on Nextcloud.

So, is it possible to add folder support?

**Comment by dgmid** [comment]
Hi @kdbruin I'm currently working on folders and they will be available in the next release (v2.0.3)

**Comment by dgmid** [comment]
v2.0.3 with support for folders has been released

https://github.com/dgmid/nextcloud-bookmark-manager/releases/tag/v2.0.3

**Comment by kdbruin** [comment]
Thanks! Will check it out this weekend.
