### ISSUE TITLE
Compatibility with Bookmarks 0.16.0

### ISSUE THREAD

**Issue by mundschenk-at** [dgmid/nextcloud-bookmark-manager#5]
Apparently there is an issue with Bookmarks 0.16.0:

`ArgumentCountError: Too few arguments to function OCA\Bookmarks\Controller\Rest\BookmarkController::__construct(), 8 passed in /srv/nextcloud/apps/bookmarks/appinfo/application.php on line 72 and exactly 9 expected`

**Comment by dgmid** [comment]
Can you give me more details? What did you do to get this error?

**Comment by mundschenk-at** [comment]
Ah, sorry. This happens when trying to synchronize the bookmarks (so basically you can't do anything other than enter your login credentials).

**Comment by dgmid** [comment]
I can't recreate this. I'm using:
Nextcloud 15.0.2
Bookamarks 0.16.0
and Nextcloud Bookmark Manager 1.1.2

I've revoked my access token, and deleted all app prefs ( ~/Library/Application Support/Nextcloud Bookmark Manager/ )
but I can still create a new conection, add, edit etc...

Are you, by any chance using an older version of Nextcloud Bookmark Manager?
The most recent is 1.1.2

**Comment by mundschenk-at** [comment]
I'm using 1.1.2 downloaded from your website. However, I'm still on Nextcloud 14.0.6 (15.0.2 is not yet available in the `stable` channel).

**Comment by mundschenk-at** [comment]
I just tried this via the web interface and it looks like it is an issue with Bookmarks 0.16.0 and Nextcloud 14.x.

**Comment by mundschenk-at** [comment]
It was an opcache issue. Apparently the update didn't trigger a complete enough refresh. Reloading `php-fpm` did the trick. Sorry for the bother.

**Comment by dgmid** [comment]
No problem - happy everything is OK.
