### ISSUE TITLE
Add support for Linux and Windows?

### ISSUE THREAD

**Issue by e-alfred** [dgmid/nextcloud-bookmark-manager#7]
Hello,

this app looks quite nice, can you make a port for Linux and Windows? As it is written in Electron this might be doable with relatively low effort? Are there some pieces that are MacOS-specific?

**Comment by dgmid** [comment]
As it is this app contains nothing that is Mac specific, so it should be straight forward to add support for Linux and Windows, however I currently have no means of testing on those platforms.
The code is here on github and anyone is welcome to fork it and make the necessary modifications.

**Comment by e-alfred** [comment]
I built your app for Windows and Linux by changing this line: https://github.com/dgmid/nextcloud-bookmark-manager/commit/cabbaabdaa1632e350c12b9f47f006bcad1cb3a8

I use it for months now and it works pretty well.

**Comment by e-alfred** [comment]
I released builds for Linux and Windows (64 bit) on my forc:

https://github.com/e-alfred/nextcloud-bookmark-manager/releases/tag/2.0.2

The only incompatibility I found is the context menu for selecting a browser which relies on Applescript:

https://github.com/dgmid/nextcloud-bookmark-manager/blob/951466556a679b8f2b615be8943813820b82ec3c/app-source/js/menu-bookmarks.js#L86

**Comment by dgmid** [comment]
@e-alfred That's fantastic, thanks!

Yes, the browser menu uses AppleScript to open the selected browser - that would need to be commented out for Win / Linux.
Other things to check perhaps would be that all the menu commands are valid also for Win / Linux, and also preload.js

In preload.js there is a check to see what version of MacOS is being used. Based on the version the app decides wether to use accent colors or the default mac blue for selections. Probably under Win / Linux it's defaulting to blue -- but it may need to be checked.

**Comment by dgmid** [comment]
@e-alfred with regards to the use of applescript for opening selected browsers -- the next release (v2.0.3) will no longer be using applescript. I'm now using [detect-browsers](https://github.com/Subash/detect-browsers) to directly find and open installed browsers. This should work on Linux / Win.
