### ISSUE TITLE
double-click

### ISSUE THREAD

**Issue by exekutive** [dgmid/nextcloud-bookmark-manager#8]
Hey nice app! It looks really good. What would be super nice, is if I could double-click a bookmark to open it in my browser. It doesn't seem to do that right now. I have to right click and then open.

I also love your MacOS Notes client. Finally somebody did it right! I've tried explaining developers this is how it should be, but they're too stubborn and clueless about user friendliness. But I found it completely by accident. It should really be linked from the main Nextcloud website. It blows the others out of the water.

**Comment by dgmid** [comment]
Hi,
Thanks for the suggestion.
I'll look into it.
I really need to do some work on the bookmarks app as I haven't worked on 
it for quite a while now.

When a bookmark is selected, you can use the arrow keys to move the 
selection up or down and the space-bar to open the selected bookmark. 
Double click would also be a good addition.

Glad you like the notes app!


Duncan

**Comment by dgmid** [comment]
Double click to open bookmarks has now been added and will be available in version 2.0.0
