### ISSUE TITLE
No way to close "More Info" Pop Up

### ISSUE THREAD

**Issue by sunjam** [dgmid/nextcloud-bookmark-manager#9]
I cannot find a way to close the More Info pop up, which appears after selecting _About Nextcloud Bookmark Manager_, besides exiting the entire program.  Thanks!
![Screen Shot 2019-11-10 at 7 51 21 AM](https://user-images.githubusercontent.com/1787238/68547036-afa21e00-0391-11ea-80e1-784d76016990.png)

**Comment by sunjam** [comment]
![Screen Shot 2019-11-10 at 7 51 21 AM](https://user-images.githubusercontent.com/1787238/68547023-9b5e2100-0391-11ea-83f5-25c0a7ac048b.png)

**Comment by dgmid** [comment]
This should now be fixed when is released v2.0.0
